### PR TITLE
Added a constructor

### PR DESCRIPTION
**Pull request by eleanora17**
Dear Kahlili,

Do check my code....
and do the needful

Regards,
Team member

### CODE REVIEW

**Comment by Kahlil7** [comment]
E11ienor sup?

**Comment by Leo122000** [comment]
i got it
code is checked

**Comment by eleanora17** [comment]
You are useless

**Comment by Kahlil7** [comment]
Respect the leader

**Comment by Kahlil7** [comment]
lets go to the canteen.

**Comment by eleanora17** [comment]
Yes Sir

**Comment by Kahlil7** [comment]
NOWW!!!

**Comment by eleanora17** [comment]
Ok 
BOSS!!!!

**Comment by Leo122000** [comment]
yes lol

**Pull request merged**
